package il.co.aman.itextimpl;

public class TableParams {
	
	public String CELL_table_row_type, TABLE_COL_WIDTHS, TABLE_BACKGROUND_COLOR;
	public float fLeft, fTop;
	String TABLE_BORDER_LEFT_COLOR, TABLE_BORDER_BOTTOM_COLOR, TABLE_BORDER_RIGHT_COLOR, TABLE_BORDER_TOP_COLOR,
		TABLE_BORDER_LEFT_STYLE, TABLE_BORDER_BOTTOM_STYLE, TABLE_BORDER_RIGHT_STYLE, TABLE_BORDER_TOP_STYLE;
	double TABLE_BORDER_LEFT_WIDTH, TABLE_BORDER_BOTTOM_WIDTH, TABLE_BORDER_RIGHT_WIDTH, TABLE_BORDER_TOP_WIDTH;
	
	public float[] borderWidths() {
		return new float[] {(float)this.TABLE_BORDER_LEFT_WIDTH, (float)this.TABLE_BORDER_BOTTOM_WIDTH, (float)this.TABLE_BORDER_RIGHT_WIDTH, (float)this.TABLE_BORDER_TOP_WIDTH};
	}
	
	public String[] borderColors() {
		return new String[] {this.TABLE_BORDER_LEFT_COLOR, this.TABLE_BORDER_BOTTOM_COLOR, this.TABLE_BORDER_RIGHT_COLOR, this.TABLE_BORDER_RIGHT_COLOR};
	}
	
	public String[] borderStyles() {
		return new String[] {this.TABLE_BORDER_LEFT_STYLE, this.TABLE_BORDER_BOTTOM_STYLE, this.TABLE_BORDER_RIGHT_STYLE, this.TABLE_BORDER_TOP_STYLE};
	}
	
	public TableParams() {
		
	}

	public TableParams(String CELL_table_row_type, String TABLE_COL_WIDTHS, String TABLE_BACKGROUND_COLOR, float fLeft, float fTop, double TABLE_BORDER_LEFT_WIDTH, 
				double TABLE_BORDER_BOTTOM_WIDTH, double TABLE_BORDER_RIGHT_WIDTH, double TABLE_BORDER_TOP_WIDTH, String TABLE_BORDER_LEFT_COLOR,
				String TABLE_BORDER_BOTTOM_COLOR, String TABLE_BORDER_RIGHT_COLOR, String TABLE_BORDER_TOP_COLOR, String TABLE_BORDER_LEFT_STYLE,
				String TABLE_BORDER_BOTTOM_STYLE, String TABLE_BORDER_RIGHT_STYLE, String TABLE_BORDER_TOP_STYLE) {
		this.CELL_table_row_type = CELL_table_row_type;
		this.TABLE_COL_WIDTHS = TABLE_COL_WIDTHS;
		this.TABLE_BACKGROUND_COLOR = TABLE_BACKGROUND_COLOR;
		this.fLeft = fLeft;
		this.fTop = fTop;
		this.TABLE_BORDER_LEFT_WIDTH = TABLE_BORDER_LEFT_WIDTH;
		this.TABLE_BORDER_BOTTOM_WIDTH = TABLE_BORDER_BOTTOM_WIDTH;
		this.TABLE_BORDER_RIGHT_WIDTH = TABLE_BORDER_RIGHT_WIDTH;
		this.TABLE_BORDER_TOP_WIDTH = TABLE_BORDER_TOP_WIDTH;
		this.TABLE_BORDER_LEFT_COLOR = TABLE_BORDER_LEFT_COLOR;
		this.TABLE_BORDER_BOTTOM_COLOR = TABLE_BORDER_BOTTOM_COLOR;
		this.TABLE_BORDER_RIGHT_COLOR = TABLE_BORDER_RIGHT_COLOR;
		this.TABLE_BORDER_TOP_COLOR = TABLE_BORDER_TOP_COLOR;
		this.TABLE_BORDER_LEFT_STYLE = TABLE_BORDER_LEFT_STYLE;
		this.TABLE_BORDER_BOTTOM_STYLE = TABLE_BORDER_BOTTOM_STYLE;
		this.TABLE_BORDER_RIGHT_STYLE = TABLE_BORDER_RIGHT_STYLE;
		this.TABLE_BORDER_TOP_STYLE = TABLE_BORDER_TOP_STYLE;
	}
}
